### ISSUE TITLE
使用 make run 启动内核时出现问题

### ISSUE THREAD

**Issue by XIA-Jinyi** [Cassie-Lim/UCAS_OSlab_2022#1]
在 Project 1 的任务 1 中，我根据指导书的要求，编写好了打印字符串的部分。

```s
la a0, msg
li a7, BIOS_PUTSTR
call bios_func_entry
```

使用提供的 createimage 构建镜像后，执行 `make run` 启动 qemu，提示 **Invalid partition 1**，且未能正常打印字符串。使用 `md 0x50200000 0x10` 查看内存内容，发现 bootblock 已经加载至指定内存位置（如下图）。**请问正常运行的效果应该是什么样的（如果能给出正常运行的效果截图就更好了）？此处 Invalid partition 1 是否会影响实验？**

![image](https://github.com/Cassie-Lim/UCAS_OSlab_2022/assets/84257087/75de3d99-0e42-4cfe-b1e3-90c069fc2b7a)

为了解决该问题，我尝试用 gdb 进行调试（如下图）。我在 bootblock 起始位置 `0x50200000` 处设置了断点，但是在调试过程中一直未触发，说明系统未执行至该位置的指令。等待系统运行后，查看 `0x50200000` 处的反汇编指令，发现 bootblock 已被成功加载。多次给出中断信号，发现系统均运行至 `0x500ffb50` 处。查看该处的反汇编指令，发现此处疑似为一个死循环（`0x500ffb66` 处的指令无条件跳转至 `0x500ffb50`）。调试过程中未能找出问题的原因。

![image](https://github.com/Cassie-Lim/UCAS_OSlab_2022/assets/84257087/b91e6a5c-f864-47e1-a9f7-7454950e9bd6)

**Comment by geotle77** [comment]
Invalid partition 1是没问题的，正常启动就会这样。之所以你没有打印出内容，可能是因为你没有输入loadboot启动内核，所以现在是在循环中等待触发。

**Comment by XIA-Jinyi** [comment]
解决了，感谢回答！
